"""SQLAlchemy migration template.

This template is used by Alembic for all migrations generated for Campus Nexus.
"""
"""Initial migration

Revision ID: 36c1750df49a
Revises: 
Create Date: 2026-09-01 22:35:27.263770

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '36c1750df49a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    pass
